global using Microsoft.EntityFrameworkCore;
global using ProjectManagerBackend.Repo.Data;
global using ProjectManagerBackend.Repo.Models;
global using ProjectManagerBackend.Repo.Repositories;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using ProjectManagerBackend.API.Controllers;
global using ProjectManagerBackend.Repo.DTOs;
global using ProjectManagerBackend.Repo.Interfaces;